### 
@baseUrl = http://localhost:3000
###

### criar uma fazenda

POST {{baseUrl}}/fazenda
Content-Type: application/json

{
    "responsavel_id": "1",
    "nome": "Fazenda do João"
}

### atualizar uma fazenda

PUT {{baseUrl}}/fazenda
Content-Type: application/json

{
    "id": "1",
    "responsavel_id": "1",
    "nome": "Fazenda do João"
}
